language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode7.3
install: true
script: make && make test
